// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwayBdVFiUMHeK8Q6W2Zx7PJYSmAzE1M0',
    appId: '1:89162094153:web:c3572f141629eba8bbd198',
    messagingSenderId: '89162094153',
    projectId: 'e-hospital-46b0d',
    authDomain: 'e-hospital-46b0d.firebaseapp.com',
    storageBucket: 'e-hospital-46b0d.firebasestorage.app',
    measurementId: 'G-LP6PQDN10L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4s8JN4k-CAXzp8GEQEKuj_xoQsZ8HKb4',
    appId: '1:89162094153:android:82cb57747eb7ae1bbbd198',
    messagingSenderId: '89162094153',
    projectId: 'e-hospital-46b0d',
    storageBucket: 'e-hospital-46b0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaO2ybiiGT5JR9fB0YeFz7lwwCRa_k0Yw',
    appId: '1:89162094153:ios:5b08db26bbd61993bbd198',
    messagingSenderId: '89162094153',
    projectId: 'e-hospital-46b0d',
    storageBucket: 'e-hospital-46b0d.firebasestorage.app',
    iosBundleId: 'com.example.eHospital',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaO2ybiiGT5JR9fB0YeFz7lwwCRa_k0Yw',
    appId: '1:89162094153:ios:5b08db26bbd61993bbd198',
    messagingSenderId: '89162094153',
    projectId: 'e-hospital-46b0d',
    storageBucket: 'e-hospital-46b0d.firebasestorage.app',
    iosBundleId: 'com.example.eHospital',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwayBdVFiUMHeK8Q6W2Zx7PJYSmAzE1M0',
    appId: '1:89162094153:web:6379200a84b327b5bbd198',
    messagingSenderId: '89162094153',
    projectId: 'e-hospital-46b0d',
    authDomain: 'e-hospital-46b0d.firebaseapp.com',
    storageBucket: 'e-hospital-46b0d.firebasestorage.app',
    measurementId: 'G-DFJ7KW95KJ',
  );
}
